# Model Development
In data analytics, Model Development is often used to help us predict future observations from the data we have.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("DataSets/TheCars_Dev.csv")
df

symboling  normalized-losses         make aspiration num-of-doors  \
0            3                122  alfa-romero        std          two   
1            3                122  alfa-romero        std          two   
2            1                122  alfa-romero        std          two   
3            2                164         audi        std         four   
4            2                164         audi        std         four   
..         ...                ...          ...        ...          ...   
196         -1                 95        volvo        std         four   
197         -1                 95        volvo      turbo         four   
198         -1                 95        volvo        std         four   
199         -1                 95        volvo      turbo         four   
200         -1                 95        volvo      turbo         four   

      body-style drive-wheels engine-location  wheel-base    length  ...  \
0    convertible          rwd           front        88.6  0.811148  ...   
1    convertible          rwd           front        88.6  0.811148  ...   
2      hatchback          rwd           front        94.5  0.822681  ...   
3          sedan          fwd           front        99.8  0.848630  ...   
4          sedan          4wd           front        99.4  0.848630  ...   
..           ...          ...             ...         ...       ...  ...   
196        sedan          rwd           front       109.1  0.907256  ...   
197        sedan          rwd           front       109.1  0.907256  ...   
198        sedan          rwd           front       109.1  0.907256  ...   
199        sedan          rwd           front       109.1  0.907256  ...   
200        sedan          rwd           front       109.1  0.907256  ...   

     compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                  9.0       111.0    5000.0       21          27  13495.0   
1                  9.0       111.0    5000.0       21          27  16500.0   
2                  9.0       154.0    5000.0       19          26  16500.0   
3                 10.0       102.0    5500.0       24          30  13950.0   
4                  8.0       115.0    5500.0       18          22  17450.0   
..                 ...         ...       ...      ...         ...      ...   
196                9.5       114.0    5400.0       23          28  16845.0   
197                8.7       160.0    5300.0       19          25  19045.0   
198                8.8       134.0    5500.0       18          23  21485.0   
199               23.0       106.0    4800.0       26          27  22470.0   
200                9.5       114.0    5400.0       19          25  22625.0   

    city-L/100km  horsepower-binned  diesel  gas  
0      11.190476             Medium       0    1  
1      11.190476             Medium       0    1  
2      12.368421             Medium       0    1  
3       9.791667             Medium       0    1  
4      13.055556             Medium       0    1  
..           ...                ...     ...  ...  
196    10.217391             Medium       0    1  
197    12.368421               High       0    1  
198    13.055556             Medium       0    1  
199     9.038462             Medium       1    0  
200    12.368421             Medium       0    1  

[201 rows x 29 columns]

In [10]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'aspiration', 'num-of-doors',
       'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length',
       'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
       'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio',
       'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price',
       'city-L/100km', 'horsepower-binned', 'diesel', 'gas'],
      dtype='object')

# 1.Linear Regression and Multiple Linear Regression

## Linear Regression

<b>Simple Linear Regression</b>

<p>Simple Linear Regression is a method to help us understand the relationship between two variables:</p>
<ul>
    <li>The predictor/independent variable (X)</li>
    <li>The response/dependent variable (that we want to predict)(Y)</li>
</ul>

<p>The result of Linear Regression is a <b>linear function</b> that predicts the response (dependent) variable as a function of the predictor (independent) variable.</p>

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
lm = LinearRegression()
lm

LinearRegression()

<h4>How could "highway-mpg" help us predict car price?</h4>
Using simple linear regression, we will create a linear function with "highway-mpg" as the predictor variable and the "price" as the response variable.

In [14]:
X = df[["highway-mpg"]]
Y = df["price"]
lm.fit(X, Y)

LinearRegression()

In [16]:
Yhat = lm.predict(X)
Yhat[0:5]

array([16236.50464347, 16236.50464347, 17058.23802179, 13771.3045085 ,
       20345.17153508])

In [17]:
lm.intercept_

38423.3058581574

In [18]:
lm.coef_

array([-821.73337832])

In [19]:
Price_highway_mpg = 38423.31 - 821.73 * df[["highway-mpg"]]
Price_highway_mpg 

highway-mpg
0       16236.60
1       16236.60
2       17058.33
3       13771.41
4       20345.25
..           ...
196     15414.87
197     17880.06
198     19523.52
199     16236.60
200     17880.06

[201 rows x 1 columns]

In [20]:
lm1 = LinearRegression()
lm1.fit(df[["engine-size"]], df["price"])
print(lm1.intercept_)
print(lm1.coef_)

-7963.338906281024
[166.86001569]


In [21]:
Price_engine_size = -7963.34 + 166.86 * df[["engine-size"]]
Price_engine_size

engine-size
0       13728.46
1       13728.46
2       17399.38
3       10224.40
4       14729.62
..           ...
196     15563.92
197     15563.92
198     20903.44
199     16231.36
200     15563.92

[201 rows x 1 columns]

# Multiple Linear Regression
<p>Other good predictors of price could be:</p>
<ul>
    <li>Horsepower</li>
    <li>Curb-weight</li>
    <li>Engine-size</li>
    <li>Highway-mpg</li>
</ul>

Developing a model using these variables as the predictor variables.

In [25]:
z = df[["horsepower", "curb-weight", "engine-size", "highway-mpg"]]
lm.fit(z, df["price"])
print(lm.intercept_)
print(lm.coef_)

-15806.624626329227
[53.49574423  4.70770099 81.53026382 36.05748882]


##### Creating and training a Multiple Linear Regression model "lm2" where the response variable is "price", and the predictor variable is "normalized-losses" and "highway-mpg".

In [26]:
lm2 = LinearRegression()

lm2.fit(df[["normalized-losses", "highway-mpg"]], df["price"])

print(lm2.intercept_)
print(lm2.coef_)

38201.31327245728
[   1.49789586 -820.45434016]
